server:
  port: 7452

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

spring:
  application:
    name: shop
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    password: 7452
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
